/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as CheckoutIndexImport } from './routes/checkout/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as HomeIndexImport } from './routes/_home/index'
import { Route as AuthProtectedImport } from './routes/_auth/protected'
import { Route as PublicRegisterIndexImport } from './routes/_public/register/index'
import { Route as PublicLoginIndexImport } from './routes/_public/login/index'
import { Route as RootDashboardsResturantOwnerOrdersIndexImport } from './routes/_root/_dashboards/_resturant-owner/orders/index'
import { Route as RootDashboardsResturantOwnerMenuIndexImport } from './routes/_root/_dashboards/_resturant-owner/menu/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutIndexRoute = CheckoutIndexImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthProtectedRoute = AuthProtectedImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => AuthRoute,
} as any)

const PublicRegisterIndexRoute = PublicRegisterIndexImport.update({
  id: '/_public/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const PublicLoginIndexRoute = PublicLoginIndexImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const RootDashboardsResturantOwnerOrdersIndexRoute =
  RootDashboardsResturantOwnerOrdersIndexImport.update({
    id: '/_root/_dashboards/_resturant-owner/orders/',
    path: '/orders/',
    getParentRoute: () => rootRoute,
  } as any)

const RootDashboardsResturantOwnerMenuIndexRoute =
  RootDashboardsResturantOwnerMenuIndexImport.update({
    id: '/_root/_dashboards/_resturant-owner/menu/',
    path: '/menu/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/protected': {
      id: '/_auth/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof AuthProtectedImport
      parentRoute: typeof AuthImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/_root/_dashboards/_resturant-owner/menu/': {
      id: '/_root/_dashboards/_resturant-owner/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof RootDashboardsResturantOwnerMenuIndexImport
      parentRoute: typeof rootRoute
    }
    '/_root/_dashboards/_resturant-owner/orders/': {
      id: '/_root/_dashboards/_resturant-owner/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof RootDashboardsResturantOwnerOrdersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthProtectedRoute: typeof AuthProtectedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProtectedRoute: AuthProtectedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/protected': typeof AuthProtectedRoute
  '/': typeof HomeIndexRoute
  '/about': typeof AboutIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/menu': typeof RootDashboardsResturantOwnerMenuIndexRoute
  '/orders': typeof RootDashboardsResturantOwnerOrdersIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/protected': typeof AuthProtectedRoute
  '/': typeof HomeIndexRoute
  '/about': typeof AboutIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/menu': typeof RootDashboardsResturantOwnerMenuIndexRoute
  '/orders': typeof RootDashboardsResturantOwnerOrdersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/protected': typeof AuthProtectedRoute
  '/_home/': typeof HomeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
  '/_root/_dashboards/_resturant-owner/menu/': typeof RootDashboardsResturantOwnerMenuIndexRoute
  '/_root/_dashboards/_resturant-owner/orders/': typeof RootDashboardsResturantOwnerOrdersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/protected'
    | '/'
    | '/about'
    | '/checkout'
    | '/login'
    | '/register'
    | '/menu'
    | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/protected'
    | '/'
    | '/about'
    | '/checkout'
    | '/login'
    | '/register'
    | '/menu'
    | '/orders'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/protected'
    | '/_home/'
    | '/about/'
    | '/checkout/'
    | '/_public/login/'
    | '/_public/register/'
    | '/_root/_dashboards/_resturant-owner/menu/'
    | '/_root/_dashboards/_resturant-owner/orders/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
  RootDashboardsResturantOwnerMenuIndexRoute: typeof RootDashboardsResturantOwnerMenuIndexRoute
  RootDashboardsResturantOwnerOrdersIndexRoute: typeof RootDashboardsResturantOwnerOrdersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
  RootDashboardsResturantOwnerMenuIndexRoute:
    RootDashboardsResturantOwnerMenuIndexRoute,
  RootDashboardsResturantOwnerOrdersIndexRoute:
    RootDashboardsResturantOwnerOrdersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_home/",
        "/about/",
        "/checkout/",
        "/_public/login/",
        "/_public/register/",
        "/_root/_dashboards/_resturant-owner/menu/",
        "/_root/_dashboards/_resturant-owner/orders/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/protected"
      ]
    },
    "/_auth/protected": {
      "filePath": "_auth/protected.tsx",
      "parent": "/_auth"
    },
    "/_home/": {
      "filePath": "_home/index.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/checkout/": {
      "filePath": "checkout/index.tsx"
    },
    "/_public/login/": {
      "filePath": "_public/login/index.tsx"
    },
    "/_public/register/": {
      "filePath": "_public/register/index.tsx"
    },
    "/_root/_dashboards/_resturant-owner/menu/": {
      "filePath": "_root/_dashboards/_resturant-owner/menu/index.tsx"
    },
    "/_root/_dashboards/_resturant-owner/orders/": {
      "filePath": "_root/_dashboards/_resturant-owner/orders/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
