/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as AuthProtectedImport } from './routes/_auth/protected'
import { Route as RootDashboardsResturantOwnerIndexImport } from './routes/_root/_dashboards/_resturant-owner/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const AuthProtectedRoute = AuthProtectedImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => AuthRoute,
} as any)

const RootDashboardsResturantOwnerIndexRoute =
  RootDashboardsResturantOwnerIndexImport.update({
    id: '/_root/_dashboards/_resturant-owner/',
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/protected': {
      id: '/_auth/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof AuthProtectedImport
      parentRoute: typeof AuthImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/_root/_dashboards/_resturant-owner/': {
      id: '/_root/_dashboards/_resturant-owner/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootDashboardsResturantOwnerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthProtectedRoute: typeof AuthProtectedRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProtectedRoute: AuthProtectedRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/protected': typeof AuthProtectedRoute
  '/about': typeof AboutIndexRoute
  '/': typeof RootDashboardsResturantOwnerIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/protected': typeof AuthProtectedRoute
  '/about': typeof AboutIndexRoute
  '/': typeof RootDashboardsResturantOwnerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/protected': typeof AuthProtectedRoute
  '/about/': typeof AboutIndexRoute
  '/_root/_dashboards/_resturant-owner/': typeof RootDashboardsResturantOwnerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/protected' | '/about' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/protected' | '/about' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/protected'
    | '/about/'
    | '/_root/_dashboards/_resturant-owner/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  RootDashboardsResturantOwnerIndexRoute: typeof RootDashboardsResturantOwnerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  RootDashboardsResturantOwnerIndexRoute:
    RootDashboardsResturantOwnerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/about/",
        "/_root/_dashboards/_resturant-owner/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/protected"
      ]
    },
    "/_auth/protected": {
      "filePath": "_auth/protected.tsx",
      "parent": "/_auth"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/_root/_dashboards/_resturant-owner/": {
      "filePath": "_root/_dashboards/_resturant-owner/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
